---
- name: Stop Tomcat
  service:
    name: tomcat
    state: stopped

- name: Search for .war files in webapps directory
  find:
    paths: "{{ tomcat_dir }}/webapps/"
    patterns: "{{ app_name }}*"
    file_type: any
  register: files_to_delete

- name: Delete old .war files from webapps directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
